"""Initial migration

Revision ID: 4acdc0d55461
Revises: 
Create Date: 2026-03-28 21:48:53.767678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = '4acdc0d55461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('consented_advisory', sa.Boolean(), nullable=True),
    sa.Column('consented_data_use', sa.Boolean(), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('prefer_sms', sa.Boolean(), nullable=True),
    sa.Column('prefer_voice', sa.Boolean(), nullable=True),
    sa.Column('prefer_push', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_phone'), 'farmers', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('broadcast_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('target_region', sa.String(), nullable=True),
    sa.Column('target_crop', sa.String(), nullable=True),
    sa.Column('scheduled_send_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_messages_id'), 'broadcast_messages', ['id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('extension_officer_id', sa.Integer(), nullable=True),
    sa.Column('farm_name', sa.String(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_harvest_date', sa.DateTime(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_nitrogen', sa.Float(), nullable=True),
    sa.Column('soil_phosphorus', sa.Float(), nullable=True),
    sa.Column('soil_potassium', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['extension_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_crop_name'), 'farms', ['crop_name'], unique=False)
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('advisory_type', sa.Enum('SOWING', 'IRRIGATION', 'FERTILIZATION', 'PEST_ALERT', 'DISEASE_ALERT', 'FROST_WARNING', 'HEAT_STRESS', name='advisorytype'), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detailed_message', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_advisory_type'), 'advisories', ['advisory_type'], unique=False)
    op.create_index(op.f('ix_advisories_id'), 'advisories', ['id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_mean', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('lead_time_hours', sa.Integer(), nullable=True),
    sa.Column('is_bias_corrected', sa.Boolean(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_forecast_date'), 'weather_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_id'), 'weather_forecasts', ['id'], unique=False)
    op.create_table('advisory_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisory_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.Enum('HELPFUL', 'NOT_HELPFUL', 'NEUTRAL', name='feedbacktype'), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_feedbacks_id'), 'advisory_feedbacks', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('advisory_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_advisory_feedbacks_id'), table_name='advisory_feedbacks')
    op.drop_table('advisory_feedbacks')
    op.drop_index(op.f('ix_weather_forecasts_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_date'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_advisories_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_advisory_type'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_crop_name'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_broadcast_messages_id'), table_name='broadcast_messages')
    op.drop_table('broadcast_messages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_farmers_phone'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
